=== Recollectionss/oop-3course/lab-2/src/candies.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    <xsd:element name="root">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="candy" type="candy" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="candy">
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="energy" type="xsd:int"/>
                <xsd:element name="type">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="Caramel"/>
                            <xsd:enumeration value="Iris"/>
                            <xsd:enumeration value="Chocolate"/>
                            <xsd:enumeration value="ChocolateWithFilling"/>
                            <xsd:enumeration value="ChocolateWithoutFilling"/>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="ingredients">
                    <xsd:complexType>
                        <xsd:all>
                            <xsd:element name="water" type="xsd:float" minOccurs="0"/>
                            <xsd:element name="sugar" type="xsd:float" minOccurs="0"/>
                            <xsd:element name="fructose" type="xsd:float" minOccurs="0"/>
                            <xsd:element name="chocolateType" type="xsd:string" minOccurs="0"/>
                            <xsd:element name="vanillin" type="xsd:float" minOccurs="0"/>
                        </xsd:all>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="value">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="proteins" type="xsd:float"/>
                            <xsd:element name="fats" type="xsd:float"/>
                            <xsd:element name="carbohydrates" type="xsd:float"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="production" type="xsd:string"/>
            </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID"/>
        </xsd:complexType>
</xsd:schema>

=== Recollectionss/oop-3course/lab-2/src/candy.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="candies.xsd"
>


    <candy id='a1'>
        <name>Example Candy</name>
        <energy>100</energy>
        <type>Chocolate</type>
        <ingredients>
            <sugar>25.0</sugar>
            <water>0.5</water>
            <fructose>10.0</fructose>
            <chocolateType>Dark</chocolateType>
            <vanillin>0.1</vanillin>
        </ingredients>
        <value>
            <proteins>1.5</proteins>
            <fats>3.0</fats>
            <carbohydrates>20.0</carbohydrates>
        </value>
        <production>Example Production</production>
    </candy>

    <candy id='a2'>
        <name>Example Candy</name>
        <energy>100</energy>
        <type>Caramel</type>
        <ingredients>
            <water>0.5</water>
            <sugar>25.0</sugar>
            <fructose>10.0</fructose>
            <chocolateType>Dark</chocolateType>
            <vanillin>0.1</vanillin>
        </ingredients>
        <value>
            <proteins>1.5</proteins>
            <fats>3.0</fats>
            <carbohydrates>20.0</carbohydrates>
        </value>
        <production>Example Production</production>
    </candy>
    <candy id='a3'>
        <name>Example Candy</name>
        <energy>100</energy>
        <type>Chocolate</type>
        <ingredients>
            <water>0.5</water>
            <sugar>25.0</sugar>
            <fructose>10.0</fructose>
            <chocolateType>Dark</chocolateType>
            <vanillin>0.1</vanillin>
        </ingredients>
        <value>
            <proteins>1.5</proteins>
            <fats>3.0</fats>
            <carbohydrates>20.0</carbohydrates>
        </value>
        <production>Example Production</production>
    </candy>
</root>
